### ISSUE TITLE
Provide Helm chart

### ISSUE THREAD

**Issue by zerodayyy** [castai/k8s-agent#53]
Looks like the only way to install cast.ai is manually running some shell command which includes `kubectl apply`. This goes against best practices and common sense in production environments where one would manage all infrastructure, including Kubernetes resources as code.
Since Helm is an industry standard, I think it would make sense to provide a Helm chart and relevant documentation on non-shell command installation method.

**Comment by saumas** [comment]
Thanks for reminding us. The helm chart was already published, just in another repo. Added more docs to help you get started!
