### ISSUE TITLE
Is it possible to host cast.ai with its dashboard oneself?

### ISSUE THREAD

**Issue by byteknacker** [castai/k8s-agent#85]
Hello, I would like to use the cost analysis feature with the dashboard but wish to self-host cast.ai. Is that possible? Or do I need to send data from my cluster to your services?

**Comment by mjur-cast** [comment]
Hey, thanks for the question. At the moment there is no such possibility.

**Comment by byteknacker** [comment]
Ok understood. If you offer that, I believe more enterprise firms will be interested in your product as data protection is important to them. Sending data to external providers can be a hindrance to enterprise adoption for regulated industries.
